# Generated by Django 3.0.7 on 2020-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0003_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_id',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
