# Generated by Django 3.0.7 on 2020-08-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0004_auto_20200807_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='india', max_length=50),
        ),
        migrations.AddField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='maharashtra', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
